server:
     port: 9001

spring:
   profiles:
       active: dev
# mybatis \u914D\u7F6E
#mybatis.type-aliases-package=tk.mybatis.springboot.model
#mybatis.mapper-locations=classpath:mapper/*.xml
# \u901A\u7528 Mapper \u914D\u7F6E
mapper:
   not-empty: false
   identity: MYSQL